<?php
/** @package It350::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("EmployeeMap.php");

/**
 * EmployeeDAO provides object-oriented access to the employees table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package It350::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class EmployeeDAO extends Phreezable
{
	/** @var string */
	public $EmployeesId;

	/** @var string */
	public $EmployeeFirstname;

	/** @var string */
	public $EmployeeLastname;

	/** @var string */
	public $Email;

	/** @var string */
	public $Title;

	/** @var string */
	public $Manager;

	/** @var string */
	public $OfficeNumber;

	/** @var date */
	public $HireDate;

	/** @var string */
	public $PhoneNumber;



}
?>